# Generated by Django 4.1.1 on 2022-09-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='my_student',
        ),
    ]
