# Generated by Django 4.1.1 on 2022-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_geeksmodel_my_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_student',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='my_student',
            name='roll_no',
            field=models.IntegerField(max_length=200),
        ),
    ]
