# Generated by Django 4.1.1 on 2022-09-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_my_student_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_student',
            name='last_modified',
        ),
    ]
