# Generated by Django 4.1.1 on 2022-09-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_my_student_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(max_length=200)),
                ('sub2', models.IntegerField(max_length=200)),
                ('sub3', models.IntegerField(max_length=200)),
                ('sub4', models.IntegerField(max_length=200)),
                ('sub5', models.IntegerField(max_length=200)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.my_student')),
            ],
        ),
    ]
